<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace OpenApi\PetStoreClient\Request;

class GetPetByIdRequest implements RequestInterface
{
    private int $petId;

    private string $contentType = '';

    private string $apiKey;

    public function __construct(int $petId, string $apiKey)
    {
        $this->petId  = $petId;
        $this->apiKey = $apiKey;
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function getRoute(): string
    {
        return strtr('pet/{petId}', ['{petId}' => $this->petId]);
    }

    public function getQueryParameters(): array
    {
        return [];
    }

    public function getRawQueryParameters(): array
    {
        return [];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return ['api_key' => $this->apiKey];
    }

    public function getBody()
    {
        return null;
    }
}
