<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace OpenApi\PetStoreClient\Request;

use OpenApi\PetStoreClient\Schema\Order;

class PlaceOrderRequest implements RequestInterface
{
    private Order $order;

    private string $contentType;

    public function __construct(Order $order, string $contentType)
    {
        $this->order       = $order;
        $this->contentType = $contentType;
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    public function getMethod(): string
    {
        return 'POST';
    }

    public function getRoute(): string
    {
        return 'store/order';
    }

    public function getQueryParameters(): array
    {
        return [];
    }

    public function getRawQueryParameters(): array
    {
        return [];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return ['Content-Type' => $this->contentType];
    }

    /**
     * @return Order
     */
    public function getBody()
    {
        return $this->order;
    }
}
