<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test;

use DoclerLabs\ApiClientException\Factory\ResponseExceptionFactory;
use Pimple\Container;
use Test\Request\Mapper\GuzzleRequestMapper;
use Test\Request\Mapper\RequestMapperInterface;
use Test\Response\ResponseHandler;
use Test\Schema\Mapper\ShowSubscriberCollectionMapper;
use Test\Schema\Mapper\ShowSubscriberMapper;
use Test\Schema\Mapper\ShowSubscribersMapper;
use Test\Serializer\BodySerializer;
use Test\Serializer\ContentType\JsonContentTypeSerializer;
use Test\Serializer\QuerySerializer;

class ServiceProvider
{
    public function register(Container $container): void
    {
        $container[BodySerializer::class] = static function (): BodySerializer {
            return (new BodySerializer())->add(new JsonContentTypeSerializer());
        };
        $container[QuerySerializer::class] = static function (): QuerySerializer {
            return new QuerySerializer();
        };
        $container[ResponseHandler::class] = static function () use ($container): ResponseHandler {
            return new ResponseHandler($container[BodySerializer::class], new ResponseExceptionFactory());
        };
        $container[RequestMapperInterface::class] = static function () use ($container): RequestMapperInterface {
            return new GuzzleRequestMapper($container[BodySerializer::class], $container[QuerySerializer::class]);
        };
        $container[ShowSubscribersMapper::class] = static function () use ($container): ShowSubscribersMapper {
            return new ShowSubscribersMapper($container[ShowSubscriberCollectionMapper::class]);
        };
        $container[ShowSubscriberCollectionMapper::class] = static function () use ($container): ShowSubscriberCollectionMapper {
            return new ShowSubscriberCollectionMapper($container[ShowSubscriberMapper::class]);
        };
        $container[ShowSubscriberMapper::class] = static function () use ($container): ShowSubscriberMapper {
            return new ShowSubscriberMapper();
        };
    }
}
