<?php declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test;

use Pimple\Container;
use Test\Response\Mapper\FoodResponseMapper;
use Test\Response\Mapper\PetCollectionResponseMapper;
use Test\Response\Mapper\PetResponseMapper;
use Test\Serializer\BodySerializer;
use Test\Serializer\ContentType\FormUrlencodedContentTypeSerializer;
use Test\Serializer\ContentType\JsonContentTypeSerializer;

class ServiceProvider
{
    /**
     * @param Container $container
     */
    private function register(Container $container): void
    {
        $container[BodySerializer::class] = static function (): BodySerializer {
            return (new BodySerializer())->add('application/json', new JsonContentTypeSerializer())->add('application/x-www-form-urlencoded', new FormUrlencodedContentTypeSerializer());
        };
        $container[PetCollectionResponseMapper::class] = static function () use ($container): PetCollectionResponseMapper {
            return new PetCollectionResponseMapper($container[PetResponseMapper::class]);
        };
        $container[PetResponseMapper::class] = static function () use ($container): PetResponseMapper {
            return new PetResponseMapper($container[FoodResponseMapper::class]);
        };
        $container[FoodResponseMapper::class] = static function () use ($container): FoodResponseMapper {
            return new FoodResponseMapper();
        };
    }
}
