<?php declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test;

use Psr\Container\ContainerInterface;
use Test\Response\Mapper\FoodResponseMapper;
use Test\Response\Mapper\PetCollectionResponseMapper;
use Test\Response\Mapper\PetResponseMapper;

class ServiceProvider
{
    /**
     * @param ContainerInterface $container
     */
    public function registerResponseMappers(ContainerInterface $container): void
    {
        $container->add(PetCollectionResponseMapper::class, static function () use ($container): PetCollectionResponseMapper {
            return new PetCollectionResponseMapper($container->get(PetResponseMapper::class));
        });
        $container->add(PetResponseMapper::class, static function () use ($container): PetResponseMapper {
            return new PetResponseMapper($container->get(FoodResponseMapper::class));
        });
        $container->add(FoodResponseMapper::class, static function () use ($container): FoodResponseMapper {
            return new FoodResponseMapper();
        });
    }
}
