<?php

use PhpCsFixer\Config;

$header = <<<'EOT'
This file was generated by docler-labs/api-client-generator.

Do not edit it manually.
EOT;

$rules = [
    '@PSR2'                                     => true,
    'array_syntax'                              => ['syntax' => 'short'],
    'no_multiline_whitespace_before_semicolons' => true,
    'no_blank_lines_after_class_opening'        => true,
    'no_short_echo_tag'                         => true,
    'no_unused_imports'                         => true,
    'blank_line_after_opening_tag'              => true,
    'not_operator_with_successor_space'         => true,
    'no_useless_else'                           => true,
    'ordered_imports'                           => [
        'sortAlgorithm' => 'alpha',
    ],
    'class_attributes_separation'               => [
        'elements' => ['const', 'method', 'property'],
    ],
    'blank_line_before_statement'               => [
        'statements' => ['break', 'continue', 'return', 'try'],
    ],
    'no_alternative_syntax'                     => true,
    'phpdoc_add_missing_param_annotation'       => true,
    'phpdoc_align'                              => [
        'align' => 'vertical',
    ],
    'phpdoc_indent'                             => true,
    'phpdoc_no_package'                         => true,
    'phpdoc_order'                              => true,
    'phpdoc_separation'                         => true,
    'phpdoc_single_line_var_spacing'            => true,
    'phpdoc_trim'                               => true,
    'phpdoc_var_without_name'                   => true,
    'phpdoc_to_comment'                         => true,
    'phpdoc_scalar'                             => [
        'types' => ['boolean', 'double', 'integer', 'real', 'str'],
    ],
    'single_quote'                              => true,
    'ternary_operator_spaces'                   => true,
    'trailing_comma_in_multiline_array'         => true,
    'trim_array_spaces'                         => true,
    'no_leading_import_slash'                   => true,
    'declare_strict_types'                      => true,
    'single_line_after_imports'                 => true,
    'header_comment'                            => [
        'header' => $header,
    ],
    'not_operator_with_space'                   => false,
    'no_spaces_inside_parenthesis'              => true,
    'unary_operator_spaces'                     => true,
    'return_type_declaration'                   => [
        'space_before' => 'none',
    ],
    'native_function_invocation'                => [
        'include' => ['@all'],
    ],
    'braces'                                    => [
        'allow_single_line_closure' => true,
    ],
    'binary_operator_spaces'                    => [
        'default' => 'align_single_space_minimal',
    ],
    'no_superfluous_phpdoc_tags'                => true,
    'no_empty_phpdoc'                           => true,
    'no_extra_blank_lines'                      => true,
];

return Config::create()
    ->setRiskyAllowed(true)
    ->setRules($rules)
    ->setIndent('    ')
    ->setUsingCache(false);
