version: '3.7'

services:
  php:
    image: php:7.4-cli-alpine
    working_dir: /app
    tty: true
    volumes:
      - .:/app

  wiremock:
    image: rodolpheche/wiremock:2.28.0-alpine
    command: ["--verbose"]
    networks:
      default:
        aliases:
          - 'pet.wiremock'

  wait:
    image: dokku/wait
