<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace OpenApi\PetStoreClient\Serializer\ContentType;

class JsonContentTypeSerializer extends AbstractJsonContentTypeSerializer
{
    public const MIME_TYPE = 'application/json';

    public function getMimeType(): string
    {
        return self::MIME_TYPE;
    }
}
