<?php declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use ArrayIterator;
use Countable;
use IteratorAggregate;

class ItemCollection implements IteratorAggregate, SerializableInterface, Countable
{
    private array $items;

    /**
     * @param Item[] $items
     */
    public function __construct(Item ...$items)
    {
        $this->items = $items;
    }

    /**
     * @return Item[]
     */
    public function toArray(): array
    {
        return $this->items;
    }

    /**
     * @return Item[]
     */
    public function getIterator(): ArrayIterator
    {
        return new ArrayIterator($this->toArray());
    }

    /**
     * @return int
     */
    public function count(): int
    {
        return \count($this->toArray());
    }

    /**
     * @return Item|null
     */
    public function first(): ?Item
    {
        $items = $this->toArray();
        $first = \reset($items);
        if ($first === false) {
            return null;
        }

        return $first;
    }
}
