<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace OpenApi\PetStoreClient\Schema\Mapper;

use OpenApi\PetStoreClient\Schema\PetCollection;

class PetCollectionMapper implements SchemaMapperInterface
{
    private PetMapper $petMapper;

    public function __construct(PetMapper $petMapper)
    {
        $this->petMapper = $petMapper;
    }

    public function toSchema(array $payload): PetCollection
    {
        $items = [];
        foreach ($payload as $payloadItem) {
            $items[] = $this->petMapper->toSchema($payloadItem);
        }

        return new PetCollection(...$items);
    }
}
