<?php declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Response\Mapper;

use DoclerLabs\ApiClientGenerator\Output\StaticPhp\Response\Mapper\ResponseMapperInterface;
use Test\Schema\ItemCollection;

class ItemCollectionResponseMapper implements ResponseMapperInterface
{
    /** @var ItemResponseMapper */
    private $itemResponseMapper;

    /**
     * @param ItemResponseMapper $itemResponseMapper
     */
    public function __construct(ItemResponseMapper $itemResponseMapper)
    {
        $this->itemResponseMapper = $itemResponseMapper;
    }

    /**
     * @param Response $response
     *
     * @return ItemCollection
     */
    public function map(Response $response): ItemCollection
    {
        $payload = $response->getPayload();
        $items   = [];
        foreach ($payload as $payloadItem) {
            $items[] = $this->itemResponseMapper->map(new Response($response->getStatusCode(), $payloadItem));
        }

        return new ItemCollection(...$items);
    }
}
