<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace OpenApi\PetStoreClient\Schema\Mapper;

use OpenApi\PetStoreClient\Schema\TagCollection;

class TagCollectionMapper implements SchemaMapperInterface
{
    private TagMapper $tagMapper;

    public function __construct(TagMapper $tagMapper)
    {
        $this->tagMapper = $tagMapper;
    }

    public function toSchema(array $payload): TagCollection
    {
        $items = [];
        foreach ($payload as $payloadItem) {
            $items[] = $this->tagMapper->toSchema($payloadItem);
        }

        return new TagCollection(...$items);
    }
}
