<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace OpenApi\PetStoreClient\Schema\Mapper;

use OpenApi\PetStoreClient\Schema\User;

class UserMapper implements SchemaMapperInterface
{
    public function toSchema(array $payload): User
    {
        $schema = new User();
        if (isset($payload['id'])) {
            $schema->setId($payload['id']);
        }
        if (isset($payload['username'])) {
            $schema->setUsername($payload['username']);
        }
        if (isset($payload['firstName'])) {
            $schema->setFirstName($payload['firstName']);
        }
        if (isset($payload['lastName'])) {
            $schema->setLastName($payload['lastName']);
        }
        if (isset($payload['email'])) {
            $schema->setEmail($payload['email']);
        }
        if (isset($payload['password'])) {
            $schema->setPassword($payload['password']);
        }
        if (isset($payload['phone'])) {
            $schema->setPhone($payload['phone']);
        }
        if (isset($payload['userStatus'])) {
            $schema->setUserStatus($payload['userStatus']);
        }

        return $schema;
    }
}
