<?php declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class ExtendedItem implements SerializableInterface, JsonSerializable
{
    private string $madatoryParentString;

    private ?int $optionalParentInteger = null;

    private int $mandatoryChildInteger;

    private ?string $optionalChildString = null;

    public function __construct(string $madatoryParentString, int $mandatoryChildInteger)
    {
        $this->madatoryParentString  = $madatoryParentString;
        $this->mandatoryChildInteger = $mandatoryChildInteger;
    }

    public function setOptionalParentInteger(int $optionalParentInteger): self
    {
        $this->optionalParentInteger = $optionalParentInteger;

        return $this;
    }

    public function setOptionalChildString(string $optionalChildString): self
    {
        $this->optionalChildString = $optionalChildString;

        return $this;
    }

    public function getMadatoryParentString(): string
    {
        return $this->madatoryParentString;
    }

    public function getOptionalParentInteger(): ?int
    {
        return $this->optionalParentInteger;
    }

    public function getMandatoryChildInteger(): int
    {
        return $this->mandatoryChildInteger;
    }

    public function getOptionalChildString(): ?string
    {
        return $this->optionalChildString;
    }

    public function toArray(): array
    {
        $fields                         = [];
        $fields['madatoryParentString'] = $this->madatoryParentString;
        if ($this->optionalParentInteger !== null) {
            $fields['optionalParentInteger'] = $this->optionalParentInteger;
        }
        $fields['mandatoryChildInteger'] = $this->mandatoryChildInteger;
        if ($this->optionalChildString !== null) {
            $fields['optionalChildString'] = $this->optionalChildString;
        }

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
