<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class ExtendedItem implements SerializableInterface, JsonSerializable
{
    private string $madatoryParentString;

    private ?int $optionalParentInteger = null;

    private int $mandatoryChildInteger;

    private ?string $optionalChildString = null;

    private ?string $optionalNullableChildString = null;

    private array $optionalPropertyChanged = ['optionalParentInteger' => false, 'optionalChildString' => false, 'optionalNullableChildString' => false];

    public function __construct(string $madatoryParentString, int $mandatoryChildInteger)
    {
        $this->madatoryParentString  = $madatoryParentString;
        $this->mandatoryChildInteger = $mandatoryChildInteger;
    }

    public function setOptionalParentInteger(int $optionalParentInteger): self
    {
        $this->optionalParentInteger                            = $optionalParentInteger;
        $this->optionalPropertyChanged['optionalParentInteger'] = true;

        return $this;
    }

    public function setOptionalChildString(string $optionalChildString): self
    {
        $this->optionalChildString                            = $optionalChildString;
        $this->optionalPropertyChanged['optionalChildString'] = true;

        return $this;
    }

    public function setOptionalNullableChildString(?string $optionalNullableChildString): self
    {
        $this->optionalNullableChildString                            = $optionalNullableChildString;
        $this->optionalPropertyChanged['optionalNullableChildString'] = true;

        return $this;
    }

    public function hasOptionalParentInteger(): bool
    {
        return $this->optionalPropertyChanged['optionalParentInteger'];
    }

    public function hasOptionalChildString(): bool
    {
        return $this->optionalPropertyChanged['optionalChildString'];
    }

    public function hasOptionalNullableChildString(): bool
    {
        return $this->optionalPropertyChanged['optionalNullableChildString'];
    }

    public function getMadatoryParentString(): string
    {
        return $this->madatoryParentString;
    }

    public function getOptionalParentInteger(): ?int
    {
        return $this->optionalParentInteger;
    }

    public function getMandatoryChildInteger(): int
    {
        return $this->mandatoryChildInteger;
    }

    public function getOptionalChildString(): ?string
    {
        return $this->optionalChildString;
    }

    public function getOptionalNullableChildString(): ?string
    {
        return $this->optionalNullableChildString;
    }

    public function toArray(): array
    {
        $fields                         = [];
        $fields['madatoryParentString'] = $this->madatoryParentString;
        if ($this->hasOptionalParentInteger()) {
            $fields['optionalParentInteger'] = $this->optionalParentInteger;
        }
        $fields['mandatoryChildInteger'] = $this->mandatoryChildInteger;
        if ($this->hasOptionalChildString()) {
            $fields['optionalChildString'] = $this->optionalChildString;
        }
        if ($this->hasOptionalNullableChildString()) {
            $fields['optionalNullableChildString'] = $this->optionalNullableChildString;
        }

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
