<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class ShowSubscribers implements SerializableInterface, JsonSerializable
{
    /** @var ShowSubscriberCollection[] */
    private $data;

    /** @var ShowSubscriberCollection[]|null */
    private $previousData;

    /** @var ShowSubscriberCollection[][]|null */
    private $groups;

    /** @var array */
    private $optionalPropertyChanged = ['previousData' => false, 'groups' => false];

    /**
     * @param ShowSubscriberCollection[] $data
     */
    public function __construct(array $data)
    {
        $this->data = $data;
    }

    /**
     * @param ShowSubscriberCollection[]|null $previousData
     */
    public function setPreviousData($previousData): self
    {
        $this->previousData                            = $previousData;
        $this->optionalPropertyChanged['previousData'] = true;

        return $this;
    }

    /**
     * @param ShowSubscriberCollection[][] $groups
     */
    public function setGroups(array $groups): self
    {
        $this->groups                            = $groups;
        $this->optionalPropertyChanged['groups'] = true;

        return $this;
    }

    public function hasPreviousData(): bool
    {
        return $this->optionalPropertyChanged['previousData'];
    }

    public function hasGroups(): bool
    {
        return $this->optionalPropertyChanged['groups'];
    }

    /**
     * @return ShowSubscriberCollection[]
     */
    public function getData(): array
    {
        return $this->data;
    }

    /**
     * @return ShowSubscriberCollection[]|null
     */
    public function getPreviousData()
    {
        return $this->previousData;
    }

    /**
     * @return ShowSubscriberCollection[][]|null
     */
    public function getGroups()
    {
        return $this->groups;
    }

    public function toArray(): array
    {
        $fields         = [];
        $fields['data'] = array_map(static function (ShowSubscriberCollection $item): array {
            return $item->toArray();
        }, $this->data);
        if ($this->hasPreviousData()) {
            $fields['previousData'] = $this->previousData !== null ? array_map(static function (ShowSubscriberCollection $item): array {
                return $item->toArray();
            }, $this->previousData) : null;
        }
        if ($this->hasGroups()) {
            $fields['groups'] = array_map(static function (array $item): array {
                return array_map(static function (ShowSubscriberCollection $item): array {
                    return $item->toArray();
                }, $item);
            }, $this->groups);
        }

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
