<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class Bird implements SerializableInterface, JsonSerializable
{
    public const TYPE_BIRD = 'bird';

    private string $type;

    private int $wingSpan;

    public function __construct(string $type, int $wingSpan)
    {
        $this->type     = $type;
        $this->wingSpan = $wingSpan;
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function getWingSpan(): int
    {
        return $this->wingSpan;
    }

    public function toArray(): array
    {
        $fields             = [];
        $fields['type']     = $this->type;
        $fields['wingSpan'] = $this->wingSpan;

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
