<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class Call implements SerializableInterface, JsonSerializable
{
    public function __construct(private readonly int $callId, private readonly CallStatus2Enum $status)
    {
    }

    public function getCallId(): int
    {
        return $this->callId;
    }

    public function getStatus(): CallStatus2Enum
    {
        return $this->status;
    }

    public function toArray(): array
    {
        $fields           = [];
        $fields['callId'] = $this->callId;
        $fields['status'] = $this->status->value;

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
