<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

enum CallStatusEnum: string
{
    case IN_PROGRESS = 'in_progress';
    case NONE        = 'none';
}
