<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class Cat implements SerializableInterface, JsonSerializable
{
    private ?bool $hunts = null;

    private ?int $age = null;

    private array $optionalPropertyChanged = ['hunts' => false, 'age' => false];

    public function setHunts(bool $hunts): self
    {
        $this->hunts                            = $hunts;
        $this->optionalPropertyChanged['hunts'] = true;

        return $this;
    }

    public function setAge(int $age): self
    {
        $this->age                            = $age;
        $this->optionalPropertyChanged['age'] = true;

        return $this;
    }

    public function hasHunts(): bool
    {
        return $this->optionalPropertyChanged['hunts'];
    }

    public function hasAge(): bool
    {
        return $this->optionalPropertyChanged['age'];
    }

    public function getHunts(): ?bool
    {
        return $this->hunts;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function toArray(): array
    {
        $fields = [];
        if ($this->hasHunts()) {
            $fields['hunts'] = $this->hunts;
        }
        if ($this->hasAge()) {
            $fields['age'] = $this->age;
        }

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
