<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class Characteristics implements SerializableInterface, JsonSerializable
{
    private ?Mammal $mammal = null;

    private ?Bird $bird = null;

    private array $optionalPropertyChanged = ['mammal' => false, 'bird' => false];

    public function setMammal(Mammal $mammal): self
    {
        $this->mammal                            = $mammal;
        $this->optionalPropertyChanged['mammal'] = true;

        return $this;
    }

    public function setBird(Bird $bird): self
    {
        $this->bird                            = $bird;
        $this->optionalPropertyChanged['bird'] = true;

        return $this;
    }

    public function hasMammal(): bool
    {
        return $this->optionalPropertyChanged['mammal'];
    }

    public function hasBird(): bool
    {
        return $this->optionalPropertyChanged['bird'];
    }

    public function getMammal(): ?Mammal
    {
        return $this->mammal;
    }

    public function getBird(): ?Bird
    {
        return $this->bird;
    }

    public function toArray(): array
    {
        $fields = [];
        if ($this->hasMammal()) {
            $fields = $this->mammal->toArray();
        }
        if ($this->hasBird()) {
            $fields = $this->bird->toArray();
        }

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
