<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class ClassSchema implements SerializableInterface, JsonSerializable
{
    private ?string $name = null;

    private array $optionalPropertyChanged = ['name' => false];

    public function setName(string $name): self
    {
        $this->name                            = $name;
        $this->optionalPropertyChanged['name'] = true;

        return $this;
    }

    public function hasName(): bool
    {
        return $this->optionalPropertyChanged['name'];
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function toArray(): array
    {
        $fields = [];
        if ($this->hasName()) {
            $fields['name'] = $this->name;
        }

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
