<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

class GetExampleResponseBody implements SerializableInterface, JsonSerializable
{
    private ?Animal $animal = null;

    private ?Machine $machine = null;

    private array $optionalPropertyChanged = ['animal' => false, 'machine' => false];

    public function setAnimal(Animal $animal): self
    {
        $this->animal                            = $animal;
        $this->optionalPropertyChanged['animal'] = true;

        return $this;
    }

    public function setMachine(Machine $machine): self
    {
        $this->machine                            = $machine;
        $this->optionalPropertyChanged['machine'] = true;

        return $this;
    }

    public function hasAnimal(): bool
    {
        return $this->optionalPropertyChanged['animal'];
    }

    public function hasMachine(): bool
    {
        return $this->optionalPropertyChanged['machine'];
    }

    public function getAnimal(): ?Animal
    {
        return $this->animal;
    }

    public function getMachine(): ?Machine
    {
        return $this->machine;
    }

    public function toArray(): array
    {
        $fields = [];
        if ($this->hasAnimal()) {
            $fields = $this->animal->toArray();
        }
        if ($this->hasMachine()) {
            $fields = $this->machine->toArray();
        }

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
