<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

enum GetModeResponseBodyEnum: string
{
    case AUTO   = 'auto';
    case MANUAL = 'manual';
}
