<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

enum GetResourcesByStatusesStatusesItemEnum: string
{
    case ACTIVE   = 'active';
    case INACTIVE = 'inactive';
    case V_7_DAYS = '+7 days';
}
