<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class HotDeal2 implements SerializableInterface, JsonSerializable
{
    private float $discountedPrice;

    public function __construct(float $discountedPrice)
    {
        $this->discountedPrice = $discountedPrice;
    }

    public function getDiscountedPrice(): float
    {
        return $this->discountedPrice;
    }

    public function toArray(): array
    {
        $fields                    = [];
        $fields['discountedPrice'] = $this->discountedPrice;

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
