<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class HotDeal implements SerializableInterface, JsonSerializable
{
    private bool $isActive;

    private ?float $discountedPrice = null;

    private array $optionalPropertyChanged = ['discountedPrice' => false];

    public function __construct(bool $isActive)
    {
        $this->isActive = $isActive;
    }

    public function setDiscountedPrice(?float $discountedPrice): self
    {
        $this->discountedPrice                            = $discountedPrice;
        $this->optionalPropertyChanged['discountedPrice'] = true;

        return $this;
    }

    public function hasDiscountedPrice(): bool
    {
        return $this->optionalPropertyChanged['discountedPrice'];
    }

    public function getIsActive(): bool
    {
        return $this->isActive;
    }

    public function getDiscountedPrice(): ?float
    {
        return $this->discountedPrice;
    }

    public function toArray(): array
    {
        $fields             = [];
        $fields['isActive'] = $this->isActive;
        if ($this->hasDiscountedPrice()) {
            $fields['discountedPrice'] = $this->discountedPrice;
        }

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
