<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

enum IntParamEnum: int
{
    case V_2 = 2;
    case V_4 = 4;
    case V_6 = 6;
}
