<?php declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class ItemMandatoryObject implements SerializableInterface, JsonSerializable
{
    /** @var string|null */
    private $string;

    /** @var ItemMandatoryObjectNullableObject|null */
    private $nullableObject;

    public function setString(string $string): self
    {
        $this->string = $string;

        return $this;
    }

    public function setNullableObject(ItemMandatoryObjectNullableObject $nullableObject): self
    {
        $this->nullableObject = $nullableObject;

        return $this;
    }

    public function getString(): ?string
    {
        return $this->string;
    }

    public function getNullableObject(): ?ItemMandatoryObjectNullableObject
    {
        return $this->nullableObject;
    }

    public function toArray(): array
    {
        $fields = [];
        if ($this->string !== null) {
            $fields['string'] = $this->string;
        }
        if ($this->nullableObject !== null) {
            $fields['nullableObject'] = $this->nullableObject->toArray();
        }

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
