<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

enum ItemOptionalIntEnum: int
{
    case V_0 = 0;
    case V_1 = 1;
    case V_2 = 2;
}
