<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class ItemWithMixed implements SerializableInterface, JsonSerializable
{
    private mixed $optionalMixed = null;

    private mixed $optionalNullableMixed = null;

    private array $optionalPropertyChanged = ['optionalMixed' => false, 'optionalNullableMixed' => false];

    /**
     * @param mixed|null $mandatoryNullableMixed
     */
    public function __construct(private readonly mixed $mandatoryMixed, private readonly mixed $mandatoryNullableMixed)
    {
    }

    public function setOptionalMixed(mixed $optionalMixed): self
    {
        $this->optionalMixed                            = $optionalMixed;
        $this->optionalPropertyChanged['optionalMixed'] = true;

        return $this;
    }

    /**
     * @param mixed|null $optionalNullableMixed
     */
    public function setOptionalNullableMixed(mixed $optionalNullableMixed): self
    {
        $this->optionalNullableMixed                            = $optionalNullableMixed;
        $this->optionalPropertyChanged['optionalNullableMixed'] = true;

        return $this;
    }

    public function hasOptionalMixed(): bool
    {
        return $this->optionalPropertyChanged['optionalMixed'];
    }

    public function hasOptionalNullableMixed(): bool
    {
        return $this->optionalPropertyChanged['optionalNullableMixed'];
    }

    public function getMandatoryMixed(): mixed
    {
        return $this->mandatoryMixed;
    }

    /**
     * @return mixed|null
     */
    public function getOptionalMixed()
    {
        return $this->optionalMixed;
    }

    /**
     * @return mixed|null
     */
    public function getOptionalNullableMixed()
    {
        return $this->optionalNullableMixed;
    }

    /**
     * @return mixed|null
     */
    public function getMandatoryNullableMixed()
    {
        return $this->mandatoryNullableMixed;
    }

    public function toArray(): array
    {
        $fields                   = [];
        $fields['mandatoryMixed'] = $this->mandatoryMixed;
        if ($this->hasOptionalMixed()) {
            $fields['optionalMixed'] = $this->optionalMixed;
        }
        if ($this->hasOptionalNullableMixed()) {
            $fields['optionalNullableMixed'] = $this->optionalNullableMixed;
        }
        $fields['mandatoryNullableMixed'] = $this->mandatoryNullableMixed;

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
