<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class MachineSpecifications implements SerializableInterface, JsonSerializable
{
    private ?int $power = null;

    private ?int $year = null;

    private array $optionalPropertyChanged = ['power' => false, 'year' => false];

    public function setPower(int $power): self
    {
        $this->power                            = $power;
        $this->optionalPropertyChanged['power'] = true;

        return $this;
    }

    public function setYear(int $year): self
    {
        $this->year                            = $year;
        $this->optionalPropertyChanged['year'] = true;

        return $this;
    }

    public function hasPower(): bool
    {
        return $this->optionalPropertyChanged['power'];
    }

    public function hasYear(): bool
    {
        return $this->optionalPropertyChanged['year'];
    }

    public function getPower(): ?int
    {
        return $this->power;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function toArray(): array
    {
        $fields = [];
        if ($this->hasPower()) {
            $fields['power'] = $this->power;
        }
        if ($this->hasYear()) {
            $fields['year'] = $this->year;
        }

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
