<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class Mammal implements SerializableInterface, JsonSerializable
{
    public const TYPE_MAMMAL = 'mammal';

    private string $type;

    private string $furColor;

    public function __construct(string $type, string $furColor)
    {
        $this->type     = $type;
        $this->furColor = $furColor;
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function getFurColor(): string
    {
        return $this->furColor;
    }

    public function toArray(): array
    {
        $fields             = [];
        $fields['type']     = $this->type;
        $fields['furColor'] = $this->furColor;

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
