<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class MatchSchema implements SerializableInterface, JsonSerializable
{
    private ?ListEnum $list = null;

    private array $optionalPropertyChanged = ['list' => false];

    public function __construct(private readonly int $id)
    {
    }

    public function setList(ListEnum $list): self
    {
        $this->list                            = $list;
        $this->optionalPropertyChanged['list'] = true;

        return $this;
    }

    public function hasList(): bool
    {
        return $this->optionalPropertyChanged['list'];
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getList(): ?ListEnum
    {
        return $this->list;
    }

    public function toArray(): array
    {
        $fields       = [];
        $fields['id'] = $this->id;
        if ($this->hasList()) {
            $fields['list'] = $this->list->value;
        }

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
