<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class Profile implements SerializableInterface, JsonSerializable
{
    private ?FailedCondition $failedCondition = null;

    private array $optionalPropertyChanged = ['failedCondition' => false];

    public function __construct(private readonly ?Membership $membership, private readonly Subscription $subscription)
    {
    }

    public function setFailedCondition(?FailedCondition $failedCondition): self
    {
        $this->failedCondition                            = $failedCondition;
        $this->optionalPropertyChanged['failedCondition'] = true;

        return $this;
    }

    public function hasFailedCondition(): bool
    {
        return $this->optionalPropertyChanged['failedCondition'];
    }

    public function getMembership(): ?Membership
    {
        return $this->membership;
    }

    public function getSubscription(): Subscription
    {
        return $this->subscription;
    }

    public function getFailedCondition(): ?FailedCondition
    {
        return $this->failedCondition;
    }

    public function toArray(): array
    {
        $fields                 = [];
        $fields['membership']   = $this->membership?->toArray();
        $fields['subscription'] = $this->subscription->toArray();
        if ($this->hasFailedCondition()) {
            $fields['failedCondition'] = $this->failedCondition?->toArray();
        }

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
