<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class PageItem implements SerializableInterface, JsonSerializable
{
    private ?HotDeal2 $hotDeal = null;

    private array $optionalPropertyChanged = ['hotDeal' => false];

    public function setHotDeal(HotDeal2 $hotDeal): self
    {
        $this->hotDeal                            = $hotDeal;
        $this->optionalPropertyChanged['hotDeal'] = true;

        return $this;
    }

    public function hasHotDeal(): bool
    {
        return $this->optionalPropertyChanged['hotDeal'];
    }

    public function getHotDeal(): ?HotDeal2
    {
        return $this->hotDeal;
    }

    public function toArray(): array
    {
        $fields = [];
        if ($this->hasHotDeal()) {
            $fields['hotDeal'] = $this->hotDeal->toArray();
        }

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
