<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

enum StringParamOneEnum: string
{
    case OPTION1 = 'option1';
    case OPTION2 = 'option2';
    case OPTION3 = 'option3';
}
