<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema;

use JsonSerializable;

class Tournament implements SerializableInterface, JsonSerializable
{
    private ?ClassSchema $class = null;

    private array $optionalPropertyChanged = ['class' => false];

    public function __construct(private readonly MatchCollection $matches)
    {
    }

    public function setClass(ClassSchema $class): self
    {
        $this->class                            = $class;
        $this->optionalPropertyChanged['class'] = true;

        return $this;
    }

    public function hasClass(): bool
    {
        return $this->optionalPropertyChanged['class'];
    }

    public function getMatches(): MatchCollection
    {
        return $this->matches;
    }

    public function getClass(): ?ClassSchema
    {
        return $this->class;
    }

    public function toArray(): array
    {
        $fields            = [];
        $fields['matches'] = $this->matches->toArray();
        if ($this->hasClass()) {
            $fields['class'] = $this->class->toArray();
        }

        return $fields;
    }

    public function jsonSerialize(): array
    {
        return $this->toArray();
    }
}
