<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

use DoclerLabs\ApiClientException\UnexpectedResponseBodyException;
use Test\Schema\GetExampleResponseBody;

class GetExampleResponseBodyMapper implements SchemaMapperInterface
{
    public function __construct(private AnimalResponseMapper $animalResponseMapper, private MachineResponseMapper $machineResponseMapper)
    {
    }

    /**
     * @throws UnexpectedResponseBodyException
     */
    public function toSchema(array $payload): GetExampleResponseBody
    {
        $schema = new GetExampleResponseBody();
        if (array_key_exists('objectType', $payload)) {
            switch ($payload['objectType']) {
                case 'animal':
                    $schema->setAnimalResponse($this->animalResponseMapper->toSchema($payload));

                    break;
                case 'machine':
                    $schema->setMachineResponse($this->machineResponseMapper->toSchema($payload));

                    break;
                default:
                    throw new UnexpectedResponseBodyException('Unknown `objectType` discriminator value for `GetExampleResponseBody` in the response body');
            }
        }

        return $schema;
    }
}
