<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

use Test\Schema\GetExampleResponseBody;

class GetExampleResponseBodyMapper implements SchemaMapperInterface
{
    public function __construct(private AnimalResponseMapper $animalResponseMapper, private MachineResponseMapper $machineResponseMapper)
    {
    }

    public function toSchema(array $payload): GetExampleResponseBody
    {
        $schema = new GetExampleResponseBody();
        if (array_key_exists('objectType', $payload)) {
            switch ($payload['objectType']) {
                case 'animal':
                    $schema->setAnimalResponse($this->animalResponseMapper->toSchema($payload));

                    break;
                case 'machine':
                    $schema->setMachineResponse($this->machineResponseMapper->toSchema($payload));

                    break;
                default:
                    $methodName = 'set' . ucfirst($payload['objectType']);
                    $mapperName = $payload['objectType'] . 'Mapper';
                    $schema->$methodName($this->$mapperName->toSchema($payload));

                    break;
            }
        }

        return $schema;
    }
}
