<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

use DoclerLabs\ApiClientException\UnexpectedResponseBodyException;
use Test\Schema\ShowSubscriberCollection;
use Test\Schema\ShowSubscribers;

class ShowSubscribersMapper implements SchemaMapperInterface
{
    private ShowSubscriberCollectionMapper $showSubscriberCollectionMapper;

    public function __construct(ShowSubscriberCollectionMapper $showSubscriberCollectionMapper)
    {
        $this->showSubscriberCollectionMapper = $showSubscriberCollectionMapper;
    }

    /**
     * @throws UnexpectedResponseBodyException
     */
    public function toSchema(array $payload): ShowSubscribers
    {
        $missingFields = implode(', ', array_diff(['data'], array_keys($payload)));
        if (!empty($missingFields)) {
            throw new UnexpectedResponseBodyException('Required attributes for `ShowSubscribers` missing in the response body: ' . $missingFields);
        }
        $schema = new ShowSubscribers(array_map(function (array $item): ShowSubscriberCollection {
            return $this->showSubscriberCollectionMapper->toSchema($item);
        }, $payload['data']));
        if (array_key_exists('previousData', $payload)) {
            $schema->setPreviousData($payload['previousData'] !== null ? array_map(function (array $item): ShowSubscriberCollection {
                return $this->showSubscriberCollectionMapper->toSchema($item);
            }, $payload['previousData']) : null);
        }
        if (isset($payload['groups'])) {
            $schema->setGroups(array_map(function (array $item): array {
                return array_map(function (array $item): ShowSubscriberCollection {
                    return $this->showSubscriberCollectionMapper->toSchema($item);
                }, $item);
            }, $payload['groups']));
        }
        if (empty($schema->toArray())) {
            throw new UnexpectedResponseBodyException();
        }

        return $schema;
    }
}
