<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

use Test\Schema\FreeFormItem;

class FreeFormItemMapper implements SchemaMapperInterface
{
    public function toSchema(array $payload): FreeFormItem
    {
        return new FreeFormItem($payload);
    }
}
