<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

use Test\Schema\Game;

class GameMapper implements SchemaMapperInterface
{
    public function __construct(private readonly MatchSchemaMapper $matchSchemaMapper, private readonly TournamentMapper $tournamentMapper)
    {
    }

    public function toSchema(array $payload): Game
    {
        $schema = new Game();
        if (array_key_exists('type', $payload)) {
            switch ($payload['type']) {
                case 'match':
                    $schema->setMatch($this->matchSchemaMapper->toSchema($payload));

                    break;
                case 'tournament':
                    $schema->setTournament($this->tournamentMapper->toSchema($payload));

                    break;
                default:
                    $methodName = 'set' . ucfirst($payload['type']);
                    $mapperName = $payload['type'] . 'Mapper';
                    $schema->$methodName($this->$mapperName->toSchema($payload));

                    break;
            }
        }

        return $schema;
    }
}
