<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

use DoclerLabs\ApiClientException\UnexpectedResponseBodyException;
use Test\Schema\ItemWithArraysOfEnumProperties;

class ItemWithArraysOfEnumPropertiesMapper implements SchemaMapperInterface
{
    /**
     * @throws UnexpectedResponseBodyException
     */
    public function toSchema(array $payload): ItemWithArraysOfEnumProperties
    {
        $missingFields = implode(', ', array_diff(['mandatoryStringEnumArray', 'mandatoryNullableStringEnumArray', 'mandatoryIntegerEnumArray'], array_keys($payload)));
        if (!empty($missingFields)) {
            throw new UnexpectedResponseBodyException('Required attributes for `ItemWithArraysOfEnumProperties` missing in the response body: ' . $missingFields);
        }
        $schema = new ItemWithArraysOfEnumProperties($payload['mandatoryStringEnumArray'], $payload['mandatoryNullableStringEnumArray'], $payload['mandatoryIntegerEnumArray']);
        if (isset($payload['optionalStringEnumArray'])) {
            $schema->setOptionalStringEnumArray($payload['optionalStringEnumArray']);
        }
        if (array_key_exists('nullableStringEnumArray', $payload)) {
            $schema->setNullableStringEnumArray($payload['nullableStringEnumArray']);
        }
        if (empty($schema->toArray())) {
            throw new UnexpectedResponseBodyException();
        }

        return $schema;
    }
}
