<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

use DoclerLabs\ApiClientException\UnexpectedResponseBodyException;
use Test\Schema\Cookie;

class CookieMapper implements SchemaMapperInterface
{
    /**
     * @throws UnexpectedResponseBodyException
     */
    public function toSchema(array $payload): Cookie
    {
        $missingFields = implode(', ', array_diff(['name', 'mandatoryNullableType'], array_keys($payload)));
        if (!empty($missingFields)) {
            throw new UnexpectedResponseBodyException('Required attributes for `Cookie` missing in the response body: ' . $missingFields);
        }
        $schema = new Cookie($payload['name'], $payload['mandatoryNullableType']);
        if (isset($payload['optionalType'])) {
            $schema->setOptionalType($payload['optionalType']);
        }
        if (array_key_exists('optionalNullableType', $payload)) {
            $schema->setOptionalNullableType($payload['optionalNullableType']);
        }
        if (array_key_exists('category', $payload)) {
            $schema->setCategory($payload['category']);
        }
        if (empty($schema->toArray())) {
            throw new UnexpectedResponseBodyException();
        }

        return $schema;
    }
}
