<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

use DoclerLabs\ApiClientException\UnexpectedResponseBodyException;
use Test\Schema\Profile;

class ProfileMapper implements SchemaMapperInterface
{
    private MembershipMapper $membershipMapper;

    private SubscriptionMapper $subscriptionMapper;

    private FailedConditionMapper $failedConditionMapper;

    public function __construct(MembershipMapper $membershipMapper, SubscriptionMapper $subscriptionMapper, FailedConditionMapper $failedConditionMapper)
    {
        $this->membershipMapper      = $membershipMapper;
        $this->subscriptionMapper    = $subscriptionMapper;
        $this->failedConditionMapper = $failedConditionMapper;
    }

    /**
     * @throws UnexpectedResponseBodyException
     */
    public function toSchema(array $payload): Profile
    {
        $missingFields = implode(', ', array_diff(['membership', 'subscription'], array_keys($payload)));
        if (!empty($missingFields)) {
            throw new UnexpectedResponseBodyException('Required attributes for `Profile` missing in the response body: ' . $missingFields);
        }
        $schema = new Profile($payload['membership'] !== null ? $this->membershipMapper->toSchema($payload['membership']) : null, $this->subscriptionMapper->toSchema($payload['subscription']));
        if (array_key_exists('failedCondition', $payload)) {
            $schema->setFailedCondition($payload['failedCondition'] !== null ? $this->failedConditionMapper->toSchema($payload['failedCondition']) : null);
        }

        return $schema;
    }
}
