<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

use DoclerLabs\ApiClientException\UnexpectedResponseBodyException;
use Test\Schema\Uploader;

class UploaderMapper implements SchemaMapperInterface
{
    private PerformerUploaderMapper $performerUploaderMapper;

    private MemberUploaderMapper $memberUploaderMapper;

    private SystemUploaderMapper $systemUploaderMapper;

    private BotUploaderMapper $botUploaderMapper;

    public function __construct(PerformerUploaderMapper $performerUploaderMapper, MemberUploaderMapper $memberUploaderMapper, SystemUploaderMapper $systemUploaderMapper, BotUploaderMapper $botUploaderMapper)
    {
        $this->performerUploaderMapper = $performerUploaderMapper;
        $this->memberUploaderMapper    = $memberUploaderMapper;
        $this->systemUploaderMapper    = $systemUploaderMapper;
        $this->botUploaderMapper       = $botUploaderMapper;
    }

    /**
     * @throws UnexpectedResponseBodyException
     */
    public function toSchema(array $payload): Uploader
    {
        $schema  = new Uploader();
        $matches = 0;

        try {
            $schema->setPerformerUploader($this->performerUploaderMapper->toSchema($payload));
            $matches = $matches + 1;
        } catch (UnexpectedResponseBodyException $exception) {
        }

        try {
            $schema->setMemberUploader($this->memberUploaderMapper->toSchema($payload));
            $matches = $matches + 1;
        } catch (UnexpectedResponseBodyException $exception) {
        }

        try {
            $schema->setSystemUploader($this->systemUploaderMapper->toSchema($payload));
            $matches = $matches + 1;
        } catch (UnexpectedResponseBodyException $exception) {
        }

        try {
            $schema->setBotUploader($this->botUploaderMapper->toSchema($payload));
            $matches = $matches + 1;
        } catch (UnexpectedResponseBodyException $exception) {
        }
        if ($matches !== 1) {
            throw new UnexpectedResponseBodyException();
        }

        return $schema;
    }
}
