<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

use DoclerLabs\ApiClientException\UnexpectedResponseBodyException;
use Test\Schema\Pet;

class PetMapper implements SchemaMapperInterface
{
    public function __construct(private readonly CatMapper $catMapper, private readonly DogMapper $dogMapper, private readonly LizardMapper $lizardMapper)
    {
    }

    /**
     * @throws UnexpectedResponseBodyException
     */
    public function toSchema(array $payload): Pet
    {
        $schema = new Pet();
        if (array_key_exists('petType', $payload)) {
            switch ($payload['petType']) {
                case 'cat':
                    $schema->setCat($this->catMapper->toSchema($payload));

                    break;
                case 'kitten':
                    $schema->setCat($this->catMapper->toSchema($payload));

                    break;
                case 'dog':
                    $schema->setDog($this->dogMapper->toSchema($payload));

                    break;
                case 'Lizard':
                case 'lizard':
                    $schema->setLizard($this->lizardMapper->toSchema($payload));

                    break;
                default:
                    throw new UnexpectedResponseBodyException('Unknown `petType` discriminator value for `Pet` in the response body');
            }
        }

        return $schema;
    }
}
