<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

use Test\Schema\OneOfResponseBody;

class OneOfResponseBodyMapper implements SchemaMapperInterface
{
    private CatMapper $catMapper;

    private DogMapper $dogMapper;

    public function __construct(CatMapper $catMapper, DogMapper $dogMapper)
    {
        $this->catMapper = $catMapper;
        $this->dogMapper = $dogMapper;
    }

    public function toSchema(array $payload): OneOfResponseBody
    {
        $schema = new OneOfResponseBody();

        try {
            $schema->setCat($this->catMapper->toSchema($payload));
        } catch (\DoclerLabs\ApiClientException\UnexpectedResponseBodyException $exception) {
        }

        try {
            $schema->setDog($this->dogMapper->toSchema($payload));
        } catch (\DoclerLabs\ApiClientException\UnexpectedResponseBodyException $exception) {
        }

        return $schema;
    }
}
