<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

use DoclerLabs\ApiClientException\UnexpectedResponseBodyException;
use Test\Schema\Uploader;
use ValueError;

class UploaderMapper implements SchemaMapperInterface
{
    public function __construct(private readonly PerformerUploaderMapper $performerUploaderMapper, private readonly MemberUploaderMapper $memberUploaderMapper, private readonly SystemUploaderMapper $systemUploaderMapper, private readonly BotUploaderMapper $botUploaderMapper)
    {
    }

    /**
     * @throws UnexpectedResponseBodyException
     */
    public function toSchema(array $payload): Uploader
    {
        $schema  = new Uploader();
        $matches = 0;

        try {
            $schema->setPerformerUploader($this->performerUploaderMapper->toSchema($payload));
            $matches = $matches + 1;
        } catch (UnexpectedResponseBodyException|ValueError $exception) {
        }

        try {
            $schema->setMemberUploader($this->memberUploaderMapper->toSchema($payload));
            $matches = $matches + 1;
        } catch (UnexpectedResponseBodyException|ValueError $exception) {
        }

        try {
            $schema->setSystemUploader($this->systemUploaderMapper->toSchema($payload));
            $matches = $matches + 1;
        } catch (UnexpectedResponseBodyException $exception) {
        }

        try {
            $schema->setBotUploader($this->botUploaderMapper->toSchema($payload));
            $matches = $matches + 1;
        } catch (UnexpectedResponseBodyException|ValueError $exception) {
        }
        if ($matches !== 1) {
            throw new UnexpectedResponseBodyException();
        }

        return $schema;
    }
}
