<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

use DoclerLabs\ApiClientException\UnexpectedResponseBodyException;
use Test\Schema\GetExampleResponseBody;

class GetExampleResponseBodyMapper implements SchemaMapperInterface
{
    private AnimalMapper $animalMapper;

    private MachineMapper $machineMapper;

    public function __construct(AnimalMapper $animalMapper, MachineMapper $machineMapper)
    {
        $this->animalMapper  = $animalMapper;
        $this->machineMapper = $machineMapper;
    }

    /**
     * @throws UnexpectedResponseBodyException
     */
    public function toSchema(array $payload): GetExampleResponseBody
    {
        $schema = new GetExampleResponseBody();
        if (array_key_exists('objectType', $payload)) {
            switch ($payload['objectType']) {
                case 'Animal':
                case 'animal':
                    $schema->setAnimal($this->animalMapper->toSchema($payload));

                    break;
                case 'Machine':
                case 'machine':
                    $schema->setMachine($this->machineMapper->toSchema($payload));

                    break;
                default:
                    throw new UnexpectedResponseBodyException('Unknown `objectType` discriminator value for `GetExampleResponseBody` in the response body');
            }
        }

        return $schema;
    }
}
