<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

use Test\Schema\PageItem;

class PageItemMapper implements SchemaMapperInterface
{
    private HotDeal2Mapper $hotDeal2Mapper;

    public function __construct(HotDeal2Mapper $hotDeal2Mapper)
    {
        $this->hotDeal2Mapper = $hotDeal2Mapper;
    }

    public function toSchema(array $payload): PageItem
    {
        $schema = new PageItem();
        if (isset($payload['hotDeal'])) {
            $schema->setHotDeal($this->hotDeal2Mapper->toSchema($payload['hotDeal']));
        }

        return $schema;
    }
}
