<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

use DateTimeImmutable;
use DoclerLabs\ApiClientException\UnexpectedResponseBodyException;
use Test\Schema\Resource;

class ResourceMapper implements SchemaMapperInterface
{
    /**
     * @throws UnexpectedResponseBodyException
     */
    public function toSchema(array $payload): Resource
    {
        $missingFields = \implode(', ', \array_diff(['mandatoryInteger', 'mandatoryString', 'mandatoryEnum', 'mandatoryDate'], \array_keys($payload)));
        if (! empty($missingFields)) {
            throw new UnexpectedResponseBodyException('Required attributes for `Resource` missing in the response body: ' . $missingFields);
        }

        return new Resource($payload['mandatoryInteger'], $payload['mandatoryString'], $payload['mandatoryEnum'], new DateTimeImmutable($payload['mandatoryDate']));
    }
}
