<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

use Test\Schema\ShowSubscriberCollection;

class ShowSubscriberCollectionMapper implements SchemaMapperInterface
{
    private ShowSubscriberMapper $showSubscriberMapper;

    public function __construct(ShowSubscriberMapper $showSubscriberMapper)
    {
        $this->showSubscriberMapper = $showSubscriberMapper;
    }

    public function toSchema(array $payload): ShowSubscriberCollection
    {
        $items = [];
        foreach ($payload as $payloadItem) {
            $items[] = $this->showSubscriberMapper->toSchema($payloadItem);
        }

        return new ShowSubscriberCollection(...$items);
    }
}
