<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Schema\Mapper;

use DoclerLabs\ApiClientException\UnexpectedResponseBodyException;
use Test\Schema\Tournament;

class TournamentMapper implements SchemaMapperInterface
{
    public function __construct(private readonly MatchCollectionMapper $matchCollectionMapper, private readonly ClassSchemaMapper $classSchemaMapper)
    {
    }

    /**
     * @throws UnexpectedResponseBodyException
     */
    public function toSchema(array $payload): Tournament
    {
        $missingFields = implode(', ', array_diff(['matches'], array_keys($payload)));
        if (!empty($missingFields)) {
            throw new UnexpectedResponseBodyException('Required attributes for `Tournament` missing in the response body: ' . $missingFields);
        }
        $schema = new Tournament($this->matchCollectionMapper->toSchema($payload['matches']));
        if (isset($payload['class'])) {
            $schema->setClass($this->classSchemaMapper->toSchema($payload['class']));
        }

        return $schema;
    }
}
