<?php declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test;

use Pimple\Container;
use Pimple\Psr11\Container as Psr11Container;
use Psr\Container\ContainerInterface;
use Psr\Http\Client\ClientInterface;

class SwaggerPetstoreClientFactory
{
    /**
     * If using Guzzle 6, make sure to configure Guzzle to not throw exceptions
     * on HTTP error status codes, or this client will violate PSR-18.
     * e.g. new Client(['base_uri' => $baseUri, 'http_errors' => false, ...])
     *
     * @param ClientInterface $client
     *
     * @return SwaggerPetstoreClient
     */
    public function create(ClientInterface $client): SwaggerPetstoreClient
    {
        return new SwaggerPetstoreClient($client, $this->initContainer());
    }

    private function initContainer(): ContainerInterface
    {
        $pimpleContainer = new Container();
        $container       = new Psr11Container($pimpleContainer);
        $serviceProvider = new ServiceProvider();
        $serviceProvider->register($pimpleContainer);

        return $container;
    }
}
