<?php declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test;

use GuzzleHttp\Client;
use Http\Adapter\Guzzle6\Client as ClientAdapter;
use InvalidArgumentException;
use Psr\Http\Client\ClientInterface;
use Test\Request\Mapper\GuzzleRequestMapper;
use Test\Request\Mapper\RequestMapperInterface;
use Test\Response\Handler\ResponseHandler;
use Test\Response\Mapper\FoodResponseMapper;
use Test\Response\Mapper\PetCollectionResponseMapper;
use Test\Response\Mapper\PetResponseMapper;
use Test\Response\ResponseMapperRegistry;
use Test\Response\ResponseMapperRegistryInterface;
use Test\Serializer\BodySerializer;

class SwaggerPetstoreClientFactory
{
    /**
     * @param string $baseUri
     * @param array  $options
     *
     * @return SwaggerPetstoreClient
     */
    public function create(string $baseUri, array $options = []): SwaggerPetstoreClient
    {
        $registry = new ResponseMapperRegistry();
        $this->registerResponseMappers($registry);

        return new SwaggerPetstoreClient($this->initBaseClient($baseUrl, $options), $this->initRequestMapper(), new ResponseHandler(), $registry);
    }

    /**
     * @param ResponseMapperRegistryInterface $registry
     */
    public function registerResponseMappers(ResponseMapperRegistryInterface $registry): void
    {
        $registry->add(PetCollectionResponseMapper::class, static function () use ($registry): PetCollectionResponseMapper {
            return new PetCollectionResponseMapper($registry->get(PetResponseMapper::class));
        });
        $registry->add(PetResponseMapper::class, static function () use ($registry): PetResponseMapper {
            return new PetResponseMapper($registry->get(FoodResponseMapper::class));
        });
        $registry->add(FoodResponseMapper::class, static function () use ($registry): FoodResponseMapper {
            return new FoodResponseMapper();
        });
    }

    private function initBaseClient(string $baseUri, array $options): ClientInterface
    {
        if (\substr($baseUri, -1) !== '/') {
            throw new InvalidArgumentException('Base URI should end with the `/` symbol.');
        }
        $default = ['base_uri' => $baseUri, 'timeout' => 3, 'http_errors' => false];
        $config  = \array_replace_recursive($default, $options);

        return new ClientAdapter(new Client($config));
    }

    private function initRequestMapper(): RequestMapperInterface
    {
        return new GuzzleRequestMapper(new BodySerializer());
    }
}
