<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace OpenApi\PetStoreClient\Request;

use OpenApi\PetStoreClient\Schema\Pet;
use OpenApi\PetStoreClient\Schema\SerializableInterface;

class AddPetRequest implements RequestInterface
{
    public const CONTENT_TYPE_APPLICATION_JSON = 'application/json';

    public const CONTENT_TYPE_APPLICATION_XML = 'application/xml';

    private string $contentType;

    private Pet $pet;

    public function __construct(string $contentType, Pet $pet)
    {
        $this->contentType = $contentType;
        $this->pet         = $pet;
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    public function getMethod(): string
    {
        return 'POST';
    }

    public function getRoute(): string
    {
        return 'pet';
    }

    public function getQueryParameters(): array
    {
        return [];
    }

    public function getRawQueryParameters(): array
    {
        return [];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return array_merge(['Content-Type' => $this->contentType], array_map(static function ($value) {
            return $value instanceof SerializableInterface ? $value->toArray() : $value;
        }, array_filter(['Content-Type' => $this->contentType], static function ($value) {
            return null !== $value;
        })));
    }

    /**
     * @return Pet
     */
    public function getBody()
    {
        return $this->pet;
    }
}
