<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace OpenApi\PetStoreClient\Request;

use OpenApi\PetStoreClient\Schema\UserCollection;

class CreateUsersWithListInputRequest implements RequestInterface
{
    private UserCollection $createUsersWithListInputRequestBody;

    private string $contentType = 'application/json';

    public function __construct(UserCollection $createUsersWithListInputRequestBody)
    {
        $this->createUsersWithListInputRequestBody = $createUsersWithListInputRequestBody;
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    public function getMethod(): string
    {
        return 'POST';
    }

    public function getRoute(): string
    {
        return 'user/createWithList';
    }

    public function getQueryParameters(): array
    {
        return [];
    }

    public function getRawQueryParameters(): array
    {
        return [];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return ['Content-Type' => $this->contentType];
    }

    /**
     * @return UserCollection
     */
    public function getBody()
    {
        return $this->createUsersWithListInputRequestBody;
    }
}
