<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace OpenApi\PetStoreClient\Request;

use OpenApi\PetStoreClient\Schema\SerializableInterface;

class DeletePetRequest implements RequestInterface
{
    private ?string $apiKey = null;

    private int $petId;

    private string $contentType = '';

    public function __construct(int $petId)
    {
        $this->petId = $petId;
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    public function setApiKey(string $apiKey): self
    {
        $this->apiKey = $apiKey;

        return $this;
    }

    public function getMethod(): string
    {
        return 'DELETE';
    }

    public function getRoute(): string
    {
        return \strtr('pet/{petId}', ['{petId}' => $this->petId]);
    }

    public function getQueryParameters(): array
    {
        return [];
    }

    public function getRawQueryParameters(): array
    {
        return [];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return \array_merge([], \array_map(static function ($value) {
            return $value instanceof SerializableInterface ? $value->toArray() : $value;
        }, \array_filter(['api_key' => $this->apiKey], static function ($value) {
            return null !== $value;
        })));
    }

    public function getBody()
    {
        return null;
    }
}
