<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace OpenApi\PetStoreClient\Request;

use OpenApi\PetStoreClient\Schema\User;

class UpdateUserRequest implements RequestInterface
{
    private string $username;

    private User $user;

    private string $contentType;

    public function __construct(string $username, User $user, string $contentType)
    {
        $this->username    = $username;
        $this->user        = $user;
        $this->contentType = $contentType;
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    public function getMethod(): string
    {
        return 'PUT';
    }

    public function getRoute(): string
    {
        return \strtr('user/{username}', ['{username}' => $this->username]);
    }

    public function getQueryParameters(): array
    {
        return [];
    }

    public function getRawQueryParameters(): array
    {
        return [];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return ['Content-Type' => $this->contentType];
    }

    /**
     * @return User
     */
    public function getBody()
    {
        return $this->user;
    }
}
