<?php declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Request\Mapper;

use Nyholm\Psr7\ServerRequest;
use Psr\Http\Message\ServerRequestInterface;
use Test\Request\RequestInterface;
use Test\Serializer\BodySerializerRegistry;

class NyholmRequestMapper implements RequestMapperInterface
{
    /** @var BodySerializerRegistry */
    private $serializerRegistry;

    /**
     * @param BodySerializerRegistry $serializerRegistry
     */
    public function __construct(BodySerializerRegistry $serializerRegistry)
    {
        $this->serializerRegistry = $serializerRegistry;
    }

    /**
     * @param RequestInterface $request
     *
     * @return ServerRequestInterface
     */
    public function map(RequestInterface $request): ServerRequestInterface
    {
        $body        = $this->serializerRegistry->getContentTypeSerializer($request->getContentType())->encode($request->getBody());
        $psr7Request = new ServerRequest($request->getMethod(), $request->getRoute(), $request->getHeaders(), $body, '1.1', []);
        $psr7Request->withQueryParams($request->getQueryParameters());
        $psr7Request->withCookieParams($request->getCookies());

        return $psr7Request;
    }
}
