<?php declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Request\Mapper;

use DoclerLabs\ApiClientGenerator\Output\StaticPhp\Request\Mapper\RequestMapperInterface;
use Nyholm\Psr7\ServerRequest;
use Psr\Http\Message\ServerRequestInterface;
use Test\Request\RequestInterface;
use Test\Serializer\BodySerializer;

class NyholmRequestMapper implements RequestMapperInterface
{
    /** @var BodySerializerInterface */
    private $serializer;

    /**
     * @param BodySerializerInterface $serializer
     */
    public function __construct(BodySerializerInterface $serializer)
    {
        $this->serializer = $serializer;
    }

    /**
     * @param RequestInterface $request
     *
     * @return ServerRequestInterface
     */
    public function map(RequestInterface $request): ServerRequestInterface
    {
        $psr7Request = new ServerRequest($request->getMethod(), $request->getRoute(), $request->getHeaders(), $this->serializer->encode($request->getBody()), '1.1', []);
        $psr7Request->withQueryParams($request->getQueryParameters());
        $psr7Request->withCookieParams($request->getCookies());

        return $psr7Request;
    }
}
