<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Request;

class AddMemberRequest implements RequestInterface
{
    private string $contentType = 'application/json';

    public function __construct(private readonly int $campaignId, private readonly int $addMemberRequestBody)
    {
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    public function getMethod(): string
    {
        return 'POST';
    }

    public function getRoute(): string
    {
        return strtr('v1/campaigns/{campaignId}/members', ['{campaignId}' => $this->campaignId]);
    }

    public function getQueryParameters(): array
    {
        return [];
    }

    public function getRawQueryParameters(): array
    {
        return [];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return ['Content-Type' => $this->contentType];
    }

    /**
     * @return LiteralRequestBody
     */
    public function getBody()
    {
        return new LiteralRequestBody($this->addMemberRequestBody);
    }
}
