<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Request;

use Test\Schema\CallStatusEnum;
use Test\Schema\CriterionStatusEq2Enum;
use Test\Schema\SerializableInterface;
use Test\Schema\StatusEnum;

class FindHostsRequest implements RequestInterface
{
    private ?CallStatusEnum $callStatus = null;

    private ?StatusEnum $status = null;

    private ?CriterionStatusEq2Enum $criterionStatusEq = null;

    private string $contentType = '';

    public function getContentType(): string
    {
        return $this->contentType;
    }

    public function setCallStatus(CallStatusEnum $callStatus): self
    {
        $this->callStatus = $callStatus;

        return $this;
    }

    public function setStatus(StatusEnum $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function setCriterionStatusEq(CriterionStatusEq2Enum $criterionStatusEq): self
    {
        $this->criterionStatusEq = $criterionStatusEq;

        return $this;
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function getRoute(): string
    {
        return 'v1/hosts';
    }

    public function getQueryParameters(): array
    {
        return array_map(static function ($value) {
            return $value instanceof SerializableInterface ? $value->toArray() : $value;
        }, array_filter(['callStatus' => $this->callStatus?->value, 'status' => $this->status?->value, 'criterion_status_eq' => $this->criterionStatusEq?->value], static function ($value) {
            return null !== $value;
        }));
    }

    public function getRawQueryParameters(): array
    {
        return ['callStatus' => $this->callStatus?->value, 'status' => $this->status?->value, 'criterion_status_eq' => $this->criterionStatusEq?->value];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return [];
    }

    public function getBody()
    {
        return null;
    }
}
