<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Request;

use DateTimeInterface;
use DoclerLabs\ApiClientException\RequestValidationException;
use Test\Schema\SerializableInterface;

class FindItemsRequest implements RequestInterface
{
    public const STATUS_ACTIVE = 'active';

    public const STATUS_INACTIVE = 'inactive';

    private ?int $limit = null;

    private ?string $name = null;

    private ?string $status = null;

    private ?DateTimeInterface $createdAfter = null;

    private ?string $xRequestSource = null;

    private ?string $session = null;

    private string $contentType = '';

    public function getContentType(): string
    {
        return $this->contentType;
    }

    /**
     * @throws RequestValidationException
     */
    public function setLimit(?int $limit): self
    {
        if ($limit !== null && $limit < 1) {
            throw new RequestValidationException(sprintf('Invalid %s value. Given: `%s`. Cannot be less than 1.', 'limit', $limit));
        }
        $this->limit = $limit;

        return $this;
    }

    /**
     * @throws RequestValidationException
     */
    public function setName(?string $name): self
    {
        if ($name !== null && grapheme_strlen($name) < 1) {
            throw new RequestValidationException(sprintf('Invalid %s value. Given: `%s`. Length should be greater than 1.', 'name', $name));
        }
        $this->name = $name;

        return $this;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function setCreatedAfter(?DateTimeInterface $createdAfter): self
    {
        $this->createdAfter = $createdAfter;

        return $this;
    }

    public function setXRequestSource(?string $xRequestSource): self
    {
        $this->xRequestSource = $xRequestSource;

        return $this;
    }

    public function setSession(?string $session): self
    {
        $this->session = $session;

        return $this;
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function getRoute(): string
    {
        return 'v1/items';
    }

    public function getQueryParameters(): array
    {
        return array_map(static function ($value) {
            return $value instanceof SerializableInterface ? $value->toArray() : $value;
        }, array_filter(['limit' => $this->limit, 'name' => $this->name, 'status' => $this->status, 'createdAfter' => $this->createdAfter], static function ($value) {
            return null !== $value;
        }));
    }

    public function getRawQueryParameters(): array
    {
        return ['limit' => $this->limit, 'name' => $this->name, 'status' => $this->status, 'createdAfter' => $this->createdAfter];
    }

    public function getCookies(): array
    {
        return array_map(static function ($value) {
            return $value instanceof SerializableInterface ? $value->toArray() : $value;
        }, array_filter(['session' => $this->session], static function ($value) {
            return null !== $value;
        }));
    }

    public function getHeaders(): array
    {
        return array_merge([], array_map(static function ($value) {
            return $value instanceof SerializableInterface ? $value->toArray() : $value;
        }, array_filter(['X-Request-Source' => $this->xRequestSource], static function ($value) {
            return null !== $value;
        })));
    }

    public function getBody()
    {
        return null;
    }
}
