<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Request;

use Test\Schema\SerializableInterface;
use Test\Schema\XPriorityEnum;
use Test\Schema\XUserTypeEnum;

class GetMessagesRequest implements RequestInterface
{
    private ?int $xUserId = null;

    private ?float $xScore = null;

    private ?bool $xPreview = null;

    private ?XPriorityEnum $xPriority = null;

    private ?XUserTypeEnum $xUserType = null;

    private string $contentType = '';

    public function __construct(private readonly int $xAccountId, private readonly bool $xDebug, private readonly string $xTraceId)
    {
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    public function setXUserId(int $xUserId): self
    {
        $this->xUserId = $xUserId;

        return $this;
    }

    public function setXScore(?float $xScore): self
    {
        $this->xScore = $xScore;

        return $this;
    }

    public function setXPreview(bool $xPreview): self
    {
        $this->xPreview = $xPreview;

        return $this;
    }

    public function setXPriority(XPriorityEnum $xPriority): self
    {
        $this->xPriority = $xPriority;

        return $this;
    }

    public function setXUserType(XUserTypeEnum $xUserType): self
    {
        $this->xUserType = $xUserType;

        return $this;
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function getRoute(): string
    {
        return 'v1/messages';
    }

    public function getQueryParameters(): array
    {
        return [];
    }

    public function getRawQueryParameters(): array
    {
        return [];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return array_merge([], array_map(static function ($value) {
            return $value instanceof SerializableInterface ? $value->toArray() : $value;
        }, array_filter(['X-Account-Id' => (string) $this->xAccountId, 'X-User-Id' => $this->xUserId === null ? null : (string) $this->xUserId, 'X-Score' => $this->xScore === null ? null : (string) $this->xScore, 'X-Debug' => $this->xDebug ? '1' : '0', 'X-Preview' => $this->xPreview === null ? null : ($this->xPreview ? '1' : '0'), 'X-Priority' => $this->xPriority === null ? null : (string) $this->xPriority->value, 'X-User-Type' => $this->xUserType?->value, 'X-Trace-Id' => $this->xTraceId], static function ($value) {
            return null !== $value;
        })));
    }

    public function getBody()
    {
        return null;
    }
}
