<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Request;

use Test\Schema\SerializableInterface;

class GetMessagesRequest implements RequestInterface
{
    public const X_USER_TYPE_MEMBER = 'member';

    public const X_USER_TYPE_PERFORMER = 'performer';

    /** @var int */
    private $xAccountId;

    /** @var int|null */
    private $xUserId;

    /** @var float|null */
    private $xScore;

    /** @var bool */
    private $xDebug;

    /** @var bool|null */
    private $xPreview;

    /** @var int|null */
    private $xPriority;

    /** @var string|null */
    private $xUserType;

    /** @var string */
    private $xTraceId;

    /** @var string */
    private $contentType = '';

    public function __construct(int $xAccountId, bool $xDebug, string $xTraceId)
    {
        $this->xAccountId = $xAccountId;
        $this->xDebug     = $xDebug;
        $this->xTraceId   = $xTraceId;
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    public function setXUserId(int $xUserId): self
    {
        $this->xUserId = $xUserId;

        return $this;
    }

    public function setXScore(?float $xScore): self
    {
        $this->xScore = $xScore;

        return $this;
    }

    public function setXPreview(bool $xPreview): self
    {
        $this->xPreview = $xPreview;

        return $this;
    }

    public function setXPriority(int $xPriority): self
    {
        $this->xPriority = $xPriority;

        return $this;
    }

    public function setXUserType(string $xUserType): self
    {
        $this->xUserType = $xUserType;

        return $this;
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function getRoute(): string
    {
        return 'v1/messages';
    }

    public function getQueryParameters(): array
    {
        return [];
    }

    public function getRawQueryParameters(): array
    {
        return [];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return array_merge([], array_map(static function ($value) {
            return $value instanceof SerializableInterface ? $value->toArray() : $value;
        }, array_filter(['X-Account-Id' => (string) $this->xAccountId, 'X-User-Id' => $this->xUserId === null ? null : (string) $this->xUserId, 'X-Score' => $this->xScore === null ? null : (string) $this->xScore, 'X-Debug' => $this->xDebug ? '1' : '0', 'X-Preview' => $this->xPreview === null ? null : ($this->xPreview ? '1' : '0'), 'X-Priority' => $this->xPriority === null ? null : (string) $this->xPriority, 'X-User-Type' => $this->xUserType, 'X-Trace-Id' => $this->xTraceId], static function ($value) {
            return null !== $value;
        })));
    }

    public function getBody()
    {
        return null;
    }
}
