<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Request;

use Test\Schema\SerializableInterface;

class GetResourcesByUntypedFilterRequest implements RequestInterface
{
    private $filter;

    private string $contentType = '';

    public function getContentType(): string
    {
        return $this->contentType;
    }

    public function setFilter($filter): self
    {
        $this->filter = $filter;

        return $this;
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function getRoute(): string
    {
        return 'v1/resources-by-untyped-filter';
    }

    public function getQueryParameters(): array
    {
        return array_map(static function ($value) {
            return $value instanceof SerializableInterface ? $value->toArray() : $value;
        }, array_filter(['filter' => $this->filter], static function ($value) {
            return null !== $value;
        }));
    }

    public function getRawQueryParameters(): array
    {
        return ['filter' => $this->filter];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return [];
    }

    public function getBody()
    {
        return null;
    }
}
