<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Request;

use Test\Schema\GetResourcesBySymbolsEmbedItemEnum;
use Test\Schema\OperatorEnum;
use Test\Schema\SerializableInterface;

class GetResourcesBySymbolsRequest implements RequestInterface
{
    private ?array $embed = null;

    private string $contentType = '';

    public function __construct(private readonly OperatorEnum $operator = OperatorEnum::EQUALS)
    {
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    /**
     * @param GetResourcesBySymbolsEmbedItemEnum[] $embed
     */
    public function setEmbed(array $embed): self
    {
        $this->embed = $embed;

        return $this;
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function getRoute(): string
    {
        return 'v1/resources-by-symbols';
    }

    public function getQueryParameters(): array
    {
        return array_map(static function ($value) {
            return $value instanceof SerializableInterface ? $value->toArray() : $value;
        }, array_filter(['operator' => $this->operator->value, 'embed' => $this->embed === null ? null : array_map(static fn (GetResourcesBySymbolsEmbedItemEnum $enum): string => $enum->value, $this->embed)], static function ($value) {
            return null !== $value;
        }));
    }

    public function getRawQueryParameters(): array
    {
        return ['operator' => $this->operator->value, 'embed' => $this->embed === null ? null : array_map(static fn (GetResourcesBySymbolsEmbedItemEnum $enum): string => $enum->value, $this->embed)];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return [];
    }

    public function getBody()
    {
        return null;
    }
}
