<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Request;

use Test\Schema\SerializableInterface;

class GetResourcesByStatusesRequest implements RequestInterface
{
    public const TYPES_BASIC = 'basic';

    public const TYPES_PREMIUM = 'premium';

    public const STATUSES_ACTIVE = 'active';

    public const STATUSES_INACTIVE = 'inactive';

    public const STATUSES_7_DAYS = '+7 days';

    private array $types;

    private ?array $statuses = null;

    private string $contentType = '';

    public function __construct(array $types)
    {
        $this->types = $types;
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    /**
     * @param string[] $statuses
     */
    public function setStatuses(array $statuses): self
    {
        $this->statuses = $statuses;

        return $this;
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function getRoute(): string
    {
        return 'v1/resources-by-statuses';
    }

    public function getQueryParameters(): array
    {
        return array_map(static function ($value) {
            return $value instanceof SerializableInterface ? $value->toArray() : $value;
        }, array_filter(['types' => $this->types, 'statuses' => $this->statuses], static function ($value) {
            return null !== $value;
        }));
    }

    public function getRawQueryParameters(): array
    {
        return ['types' => $this->types, 'statuses' => $this->statuses];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return [];
    }

    public function getBody()
    {
        return null;
    }
}
