<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Request;

use Test\Schema\SerializableInterface;

class GetResourcesBySymbolsRequest implements RequestInterface
{
    public const OPERATOR_EQUALS = '=';

    public const OPERATOR_BETWEEN = 'BETWEEN';

    public const OPERATOR_IN = 'IN';

    public const EMBED_ASTERISK = '*';

    private string $operator;

    private ?array $embed = null;

    private string $contentType = '';

    public function __construct(string $operator = '=')
    {
        $this->operator = $operator;
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    /**
     * @param string[] $embed
     */
    public function setEmbed(array $embed): self
    {
        $this->embed = $embed;

        return $this;
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function getRoute(): string
    {
        return 'v1/resources-by-symbols';
    }

    public function getQueryParameters(): array
    {
        return array_map(static function ($value) {
            return $value instanceof SerializableInterface ? $value->toArray() : $value;
        }, array_filter(['operator' => $this->operator, 'embed' => $this->embed], static function ($value) {
            return null !== $value;
        }));
    }

    public function getRawQueryParameters(): array
    {
        return ['operator' => $this->operator, 'embed' => $this->embed];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return [];
    }

    public function getBody()
    {
        return null;
    }
}
