<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Request;

use Test\Schema\GetResourcesByStatusesStatusesItemEnum;
use Test\Schema\GetResourcesByStatusesTypesItemEnum;
use Test\Schema\SerializableInterface;

class GetResourcesByStatusesRequest implements RequestInterface
{
    private ?array $statuses = null;

    private string $contentType = '';

    public function __construct(private readonly array $types)
    {
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    /**
     * @param GetResourcesByStatusesStatusesItemEnum[] $statuses
     */
    public function setStatuses(array $statuses): self
    {
        $this->statuses = $statuses;

        return $this;
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function getRoute(): string
    {
        return 'v1/resources-by-statuses';
    }

    public function getQueryParameters(): array
    {
        return array_map(static function ($value) {
            return $value instanceof SerializableInterface ? $value->toArray() : $value;
        }, array_filter(['types' => array_map(static fn (GetResourcesByStatusesTypesItemEnum $enum): string => $enum->value, $this->types), 'statuses' => $this->statuses === null ? null : array_map(static fn (GetResourcesByStatusesStatusesItemEnum $enum): string => $enum->value, $this->statuses)], static function ($value) {
            return null !== $value;
        }));
    }

    public function getRawQueryParameters(): array
    {
        return ['types' => array_map(static fn (GetResourcesByStatusesTypesItemEnum $enum): string => $enum->value, $this->types), 'statuses' => $this->statuses === null ? null : array_map(static fn (GetResourcesByStatusesStatusesItemEnum $enum): string => $enum->value, $this->statuses)];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return [];
    }

    public function getBody()
    {
        return null;
    }
}
