<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Request;

class SetNicknameRequest implements RequestInterface
{
    private ?string $setNicknameRequestBody = null;

    private string $contentType = 'application/json';

    public function __construct(?string $setNicknameRequestBody)
    {
        $this->setNicknameRequestBody = $setNicknameRequestBody;
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    public function getMethod(): string
    {
        return 'PUT';
    }

    public function getRoute(): string
    {
        return 'v1/nickname';
    }

    public function getQueryParameters(): array
    {
        return [];
    }

    public function getRawQueryParameters(): array
    {
        return [];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return ['Content-Type' => $this->contentType];
    }

    /**
     * @return LiteralRequestBody
     */
    public function getBody()
    {
        return new LiteralRequestBody($this->setNicknameRequestBody);
    }
}
