<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test\Request;

class SetTagsRequest implements RequestInterface
{
    private string $contentType = 'application/json';

    public function __construct(private readonly array $setTagsRequestBody)
    {
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    public function getMethod(): string
    {
        return 'PUT';
    }

    public function getRoute(): string
    {
        return 'v1/tags';
    }

    public function getQueryParameters(): array
    {
        return [];
    }

    public function getRawQueryParameters(): array
    {
        return [];
    }

    public function getCookies(): array
    {
        return [];
    }

    public function getHeaders(): array
    {
        return ['Content-Type' => $this->contentType];
    }

    /**
     * @return LiteralRequestBody
     */
    public function getBody()
    {
        return new LiteralRequestBody($this->setTagsRequestBody);
    }
}
