<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace OpenApi\PetStoreClient;

use Pimple\Container;
use Pimple\Psr11\Container as Psr11Container;
use Psr\Container\ContainerInterface;
use Psr\Http\Client\ClientInterface;

class SwaggerPetstoreOpenAPI3ClientFactory
{
    public function create(ClientInterface $client): SwaggerPetstoreOpenAPI3Client
    {
        return new SwaggerPetstoreOpenAPI3Client($client, $this->initContainer());
    }

    private function initContainer(): ContainerInterface
    {
        $pimpleContainer = new Container();
        $container       = new Psr11Container($pimpleContainer);
        $serviceProvider = new ServiceProvider();
        $serviceProvider->register($pimpleContainer);

        return $container;
    }
}
