name: PHPUnit tests

on:
    - push
    - pull_request

jobs:
    tests:
        runs-on: ubuntu-latest

        name: Tests on PHP 7.4

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  tools: composer:v2
                  coverage: pcov

            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist

            - name: Code style fixer
              run: vendor/bin/php-cs-fixer fix . --dry-run --diff

            - name: PHPStan
              run: vendor/bin/phpstan analyse

            - name: Run tests
              run: make test

            - name: Coveralls
              env:
                  COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: php vendor/bin/php-coveralls -v
