<?php

declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test;

use DoclerLabs\ApiClientException\UnexpectedResponseBodyException;
use Psr\Container\ContainerInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\ResponseInterface;
use Test\Request\GetClockRequest;
use Test\Request\GetLastSeenRequest;
use Test\Request\Mapper\RequestMapperInterface;
use Test\Request\RequestInterface;
use Test\Response\ResponseHandler;
use Test\Serializer\ContentType\ContentTypeSerializerInterface;

class LiteralResponsesClient
{
    public function __construct(private ClientInterface $client, private ContainerInterface $container)
    {
    }

    public function sendRequest(RequestInterface $request): ResponseInterface
    {
        return $this->client->sendRequest($this->container->get(RequestMapperInterface::class)->map($request));
    }

    public function getClock(GetClockRequest $request): string
    {
        $response = $this->handleResponse($this->sendRequest($request));

        return $response[ContentTypeSerializerInterface::LITERAL_VALUE_KEY] ?? throw new UnexpectedResponseBodyException('Response body does not contain the expected non-null value.');
    }

    public function getLastSeen(GetLastSeenRequest $request): ?string
    {
        $response = $this->handleResponse($this->sendRequest($request));

        return $response[ContentTypeSerializerInterface::LITERAL_VALUE_KEY] ?? null;
    }

    protected function handleResponse(ResponseInterface $response)
    {
        return $this->container->get(ResponseHandler::class)->handle($response);
    }
}
