<?php declare(strict_types=1);

/*
 * This file was generated by docler-labs/api-client-generator.
 *
 * Do not edit it manually.
 */

namespace Test;

use InvalidArgumentException;
use Psr\Container\ContainerInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\ResponseInterface;
use Test\Request\AddPetRequest;
use Test\Request\CountPetsRequest;
use Test\Request\DeletePetRequest;
use Test\Request\FindPetByIdRequest;
use Test\Request\FindPetsRequest;
use Test\Request\Mapper\RequestMapperInterface;
use Test\Request\RequestInterface;
use Test\Response\Handler\ErrorHandler;
use Test\Response\Mapper\PetCollectionResponseMapper;
use Test\Response\Mapper\PetResponseMapper;
use Test\Response\Mapper\ResponseMapperInterface;
use Test\Schema\Pet;
use Test\Schema\PetCollection;

class SwaggerPetstoreClient
{
    /** @var ClientInterface */
    private $client;

    /** @var RequestMapperInterface */
    private $requestMapper;

    /** @var ErrorHandler */
    private $errorHandler;

    /** @var ContainerInterface */
    private $container;

    /**
     * @param ClientInterface        $client
     * @param RequestMapperInterface $requestMapper
     * @param ErrorHandler           $errorHandler
     * @param ContainerInterface     $container
     */
    public function __construct(ClientInterface $client, RequestMapperInterface $requestMapper, ErrorHandler $errorHandler, ContainerInterface $container)
    {
        $this->client        = $client;
        $this->requestMapper = $requestMapper;
        $this->errorHandler  = $errorHandler;
        $this->container     = $container;
    }

    /**
     * @param FindPetsRequest $request
     *
     * @return PetCollection
     */
    public function findPets(FindPetsRequest $request): PetCollection
    {
        return $this->getResponseMapper(PetCollectionResponseMapper::class)->map($this->errorHandler->handle($this->sendRequest($request)));
    }

    /**
     * @param AddPetRequest $request
     *
     * @return Pet
     */
    public function addPet(AddPetRequest $request): Pet
    {
        return $this->getResponseMapper(PetResponseMapper::class)->map($this->errorHandler->handle($this->sendRequest($request)));
    }

    /**
     * @param CountPetsRequest $request
     */
    public function countPets(CountPetsRequest $request): void
    {
        $this->errorHandler->handle($this->sendRequest($request));
    }

    /**
     * @param FindPetByIdRequest $request
     *
     * @return Pet
     */
    public function findPetById(FindPetByIdRequest $request): Pet
    {
        return $this->getResponseMapper(PetResponseMapper::class)->map($this->errorHandler->handle($this->sendRequest($request)));
    }

    /**
     * @param DeletePetRequest $request
     */
    public function deletePet(DeletePetRequest $request): void
    {
        $this->errorHandler->handle($this->sendRequest($request));
    }

    /**
     * @param RequestInterface $request
     *
     * @return ResponseInterface
     */
    public function sendRequest(RequestInterface $request): ResponseInterface
    {
        return $this->client->sendRequest($this->requestMapper->map($request));
    }

    /**
     * @param string $mapperClass
     *
     * @return ResponseMapperInterface
     */
    public function getResponseMapper(string $mapperClass): ResponseMapperInterface
    {
        if (! $this->container->has($mapperClass)) {
            throw new InvalidArgumentException('Response mapper not found: ' . $mapperClass);
        }

        return $this->container->get($mapperClass);
    }
}
